# Configuration of Hugo
title: "Yan Yan - Engineering Manager"
baseurl: "https://HumbleReader.github.io/"
copyright: "© 2025 Yan Yan"

# 启用 Wowchemy 模块
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5